# Generated by Django 2.0.7 on 2018-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180825_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='amz_link',
            new_name='link',
        ),
        migrations.AddField(
            model_name='game',
            name='added_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
